
import datetime
from ai_chat_domain.model.HaleyChatDirectiveResponseMessage import HaleyChatDirectiveResponseMessage


class GetDisplayStateDirectiveResponseMessage(HaleyChatDirectiveResponseMessage):
    pass
