domains:
   - domain: "vital-domain-python"
     ontology: "vital-0.2.304.owl"
   - domain: "vital-nlp-python"
     ontology: "vital-nlp-0.2.304.owl"
   - domain: "vital-social-python"
     ontology: "vital-social-0.2.304.owl"
   - domain: "vital-aimp-python"
     ontology: "vital-aimp-0.1.0.owl"
   - domain: "vital-wordnet-python"
     ontology: "vital-wordnet-0.2.304.owl"
   - domain: "haley-python"
     ontology: "haley-0.1.0.owl"
   - domain: "haley-ai-kg-python"
     ontology: "haley-ai-kg-0.1.0.owl"
   - domain: "haley-ai-ml-python"
     ontology: "haley-ai-ml-0.1.0.owl"
   - domain: "haley-ai-question-python"
     ontology: "haley-ai-question-0.1.0.owl"
   - domain: "haley-taxonomy-python"
     ontology: "haley-taxonomy-0.1.0.owl"
   - domain: "chat-ai-python"
     ontology: "chat-ai-0.1.0.owl"
